# Bundler file
# Demo: https://github.com/carwin/bundler-demo

# Gem sources
source 'https://rubygems.org'

# The gems we require
# These will be downloaded if not present on the host system

# Compass - updated to latest preview release in order to use maps in Sass 3.3
# sudo gem update sass
# gem install compass --pre
gem 'compass', '1.0.0.alpha.19'